-- 1인 전용 앱: RLS 비활성화
-- auth.uid() 없이도 anon key로 모든 테이블에 접근 가능

ALTER TABLE user_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE basics_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE basics_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_actuals DISABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_presets DISABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_template_blocks DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_debts DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_debt_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_installments DISABLE ROW LEVEL SECURITY;
ALTER TABLE heaven_bank DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_budgets DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_budget_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_wishlist DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_recurring DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_recurring_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_onboarding DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_subscription_amount_changes DISABLE ROW LEVEL SECURITY;
ALTER TABLE finance_subscription_cancellations DISABLE ROW LEVEL SECURITY;
